@host=https://localhost:7266

GET  {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNTczZWRjMC0zNDhkLTQ3NWItYjQ3OC1kMGMwYTBlMDY1ODMiLCJnaXZlbl9uYW1lIjoiSHN1IiwiZmFtaWx5X25hbWUiOiJSb2dlciIsImp0aSI6ImRmM2JjMTllLTU5M2UtNGM2Ni1hOWJmLWRjNDRmMjVkZTI0NiIsImV4cCI6MTc2MjA2Njk1NCwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.ZmHcKAQExz-bGJug_vnzFd3K8UzyMfzGn9Gq5DzV6Rg