@host=http://localhost:5238

GET  {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YjVhZmVhZC01YzEzLTQzZWYtOGFlMS01ZDBjNWMzZDI1N2YiLCJnaXZlbl9uYW1lIjoiUm9nZXIiLCJmYW1pbHlfbmFtZSI6IkhzdSIsImp0aSI6Ijc3YTZmMDYyLWM0NDQtNDMyZC05MjZkLTZjYTdiOTU1NTBjNiIsImV4cCI6MTY5ODIyNjIyNiwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.S-f94A01dIXmzIKMjAMwEGqXlpDP4gja0W64twd96Zg